language: node_js
node_js:
#  - "6"  # LTS   from 2016-10 maintenance till 2019-04
#  - "7"  # devel from 2016-10
  - "8"  # LTS   from 2017-10 maintenance till 2019-12
#  - "9"  # devel from 2017-10
os:
  - linux
#  - osx   # not possible because of mongodb service

# run with coveralls integration
script: "npm run coverage"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "cat ./coverage/lcov.info | CODACY_PROJECT_TOKEN=6b50c72dfae44e0abd7a3da1367a6d4e ./node_modules/.bin/codacy-coverage"

# Fix the c++ compiler on Ubuntu 14.04
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
