# Configuration for production server
# =================================================


# Server listening
# -------------------------------------------------

# ### Port
#
# Set the port the server is listening on.
#
# To use a privileged port below 1024 you have to bind it using root privileges.
# This may be critical.
# The following three methods are possible to do this securely:
#
# 1.  Use sudo to start the server and change back to the normal user
#     after port binding.
#
# 2.  Start as root user but use the uid/gid setting below to change after
#     port binding
#
# 3.  Use ip-tables to forward to an unprivileged port:
#     `sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000`
#
# 4.  Use Nginx reverse-proxy on port 80 this helps also if you may run other
#     things on port 80, too.
#
# Keep in mind to use different ports for different services like HTTP and
# HTTPS. Defaults to port 23174 if not set.
port: 80

# ### trust proxy
# Indicate that the app is sitting behind a front-facing proxy, and the X-Forwarded-*
# headers may be trusted for determining the connection and the IP address of
# the client. It must, however, be noted that, the X-Forwarded-* headers are
# easily spoofed and the detected IP addresses are unreliable.
trustProxy: false


# Access restrictions
# -------------------------------------------------
# The following restrictions are possible:
#
# - `ip` give an ip address or list of addresses

# ### Whitelist
# To only allow access from specific clients they have to be listed here:
#allow:
#  ip:

# ### Blacklist
# To disallow access from specific clients list them here:
#disallow:
#  ip:


# Session handling
# -------------------------------------------------
#session:
  # The secret is used to hash the session with HMAC. The session is then
  # protected against session hijacking by checking the fingerprint against the
  # hash with the secret.
  #secret: R4FCaOCutWGN.GfVym9ag3yyPM
  # After the following time of inactivity (no server request) the session will
  # be outdated.
  #expire: 3600s


# Secure settings
# -------------------------------------------------

# This will configure the server to use SSL. Remove the complete section to
# use normal http.
#ssl:
#  key: server.key
#  cert: server.crt
#  ca: server.crt

# Debugging settings
# -------------------------------------------------
# To enable debugging set this to some possible and free ports.
#debug: false
#  port: 5858
#  inspectorPort: 3009
