# Configuration for http server
# =================================================


# Server Connections
# -------------------------------------------------
# This is list of labels with their connections to bind to. SWith this you
# have the ability to listen on multiple connections. You may connect your apps
# with specific labels, vhost and context paths.

# ### host
#
# Hostname or IP address to bind server to.

# ### port
#
# Set the port the server is listening on.
#
# To use a privileged port below 1024 you have to bind it using root privileges.
# This may be critical.
# The following three methods are possible to do this securely:
#
# 1.  Use sudo to start the server and change back to the normal user
#     after port binding.
#
# 2.  Use ip-tables to forward to an unprivileged port:
#     `sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000`
#
# 3.  Use Nginx reverse-proxy on port 80 this helps also if you may run other
#     things on port 80, too.
#
# 4.  Give Normal user capability of using sockets as root
#     sudo apt-get install libcap2-bin
#     sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
#
# Keep in mind to use different ports for different services like HTTP and
# HTTPS. Defaults to port 23174 if not set.

# ### tls
#
# The settings to use an SSL encryption on this connections:
#
# - pfx - PKCS#12 certificate containing certificate, private key and CA
#   certificates to use for SSL
# - cert - public x509 certificate to use
# - key - private key to use for SSL
# - passphrase - passphrase for the private key or pfx if necessary
# - ca - authority certificate or array of authority certificates to check
#   the remote host against"
# - ciphers - string describing the ciphers to use or exclude
#   (http://www.openssl.org/docs/apps/ciphers.html#CIPHER_LIST_FORMAT)"
# - rejectUnauthorized - lag to check server certificate against the list of
#   supplied CAs
# - secureProtocol - SSL method to use, e.g. TLSv1_method to force TLS version 1
#  (the possible values depend on your installation of OpenSSL and
#  are defined in the constant SSL_METHODS)"

# ### load
#
# The load settings will result in rejection of incoming requests with an
# "HTTP Server Timeout (503)" response if they are reached:
#
# - maxHeap - maximum V8 heap size
# - maxRss - maximum process RSS size
# - eventLoopDelay - maximum event loop delay duration in milliseconds
listener:

  default:
    #host: localhost
    port: <<<env://PORT | 23174>>>

# Log Settings
# -------------------------------------------------
# The log settings are defined as array of possible loggers.

# ### bind
#
# Like described above this will define the area of requests to log.

# ### data
#
# This is a specific format selected of the possible formats: 'error', 'event'
# 'common', 'commonvhost', 'combined', 'referrer', 'extended', 'object'.

# ### file
#

# ### http
#

# ### mail
#

log:
  - data: combined
    file:
      filename: http-access.log
      datePattern: .yyyy-MM-dd
      compress: true
  - data: error
    file:
      filename: http-error.log
      maxSize: 100MB
      compress: true
